language: php
git:
  depth: 9999999

matrix:
  include:

  - php: 7.2
    install:
    - composer install
    addons:
      sonarcloud:
        organization: "jeedom-zigate"
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer run-script test
    - sonar-scanner
  - php: 7.1
    install:
    - composer install
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer run-script test
  - php: 7.0
    install:
    - composer install
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer run-script test
  - php: 5.6
    install:
    - composer install
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - composer run-script test

  - language: python
    python:
    - 3.6
    env: TOXENV=py36
    install:
    - pip install flake8
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - flake8 .
  - language: python
    python:
    - 3.5
    env: TOXENV=py35
    install:
    - pip install flake8
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - flake8 .
  - language: python
    python:
    - 3.4
    env: TOXENV=py34
    install:
    - pip install flake8
    script:
    - cd ${TRAVIS_BUILD_DIR}
    - flake8 .

  - language: markdown
    script:
    - gem install mdl
    - cd ${TRAVIS_BUILD_DIR}
    - mdl -s markdownlint.rb *.md docs/fr_FR/*.md